name: create release
on: [push]
        
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: 1.0.1
          release_name: Release 1.0.1
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
