name: create release
on: [push]
        
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      
      - name: Resolve Version with Version File
     
        uses: pCYSl5EDgo/cat@master
        id: version
        with:
          path: VERSION
      
      - name: get commit message
        run: |
           echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
           echo $commitmsg
           
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.version.outputs.text }}
          release_name: Release ${{ steps.version.outputs.text }}
          body: |
            Changes in this Release
            - echo $commitmsg
          draft: false
          prerelease: false
      
          
