name: create release
on: [push]
        
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      
      - name: Resolve Version
     
        uses: pCYSl5EDgo/cat@master
        id: version
        with:
          path: VERSION
      - run: echo $VERSION
        env:
           VERSION: ${{ steps.version.outputs.text }}
 
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          VERSION: ${{ steps.version.outputs.text }}
        with:
          tag_name: ${{ steps.version.outputs.text }}
          release_name: Release ${{ steps.version.outputs.text }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      
          
